export default {
  GET_TRANSACTIONS_BEGIN: 'GET_TRANSACTIONS_BEGIN',
  GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILURE: 'GET_TRANSACTIONS_FAILURE',

  GET_GOAL_PROGRESS_BEGIN: 'GET_GOAL_PROGRESS_BEGIN',
  GET_GOAL_PROGRESS_SUCCESS: 'GET_GOAL_PROGRESS_SUCCESS',
  GET_GOAL_PROGRESS_FAILURE: 'GET_GOAL_PROGRESS_FAILURE',

  LIKE_TRANSACTION_BEGIN: 'LIKE_TRANSACTION_BEGIN',
  LIKE_TRANSACTION_SUCCESS: 'LIKE_TRANSACTION_SUCCESS',
  LIKE_TRANSACTION_FAILURE: 'LIKE_TRANSACTION_FAILURE'
};
