engines:
  eslint:
    enabled: true

ratings:
  paths:
  - src/**

exclude_paths:
- lib/**
- bin/**
- config/**
- cordova/**
- dist/**
- docker/**
- fastlane/**
- node_modules/**
- reports/**
- script/**
- test/**
