version: "2"

checks:
  method-lines:
    enabled: false

plugins:
  duplication:
    enabled: true
  markdownlint:
    enabled: true

exclude_patterns:
  - lib/**
  - bin/**
  - config/**
  - cordova/**
  - dist/**
  - docker/**
  - fastlane/**
  - node_modules/**
  - reports/**
  - script/**
  - test/**
