version: "2" # required to adjust maintainability checks
checks:
  method-lines:
    config:
      threshold: 80
exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/*.d.ts"
  - "**/*.spec.tsx"
  - "**/spec_helper.tsx"
  - "**/*.stories.tsx"
  - "**/PullToRefresh.js"
