language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run prettier:check
  - npm run eslint
  - npm run stylelint
  - npm run build
