language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run prettier:check
  - npm run eslint
  - npm run stylelint
  - apollo queries:check
  - npm run build
