language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn prettier --check "./src/**/*.?(tsx|js|scss)"
  - yarn eslint ./src --ext .js,.jsx,.ts,.tsx
  - yarn test