export default {
  GET_TRANSACTIONS_BEGIN: "GET_TRANSACTIONS_BEGIN",
  GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
  GET_TRANSACTIONS_FAILURE: "GET_TRANSACTIONS_FAILURE",

  GET_TRANSACTION_BEGIN: "GET_TRANSACTION_BEGIN",
  GET_TRANSACTION_SUCCESS: "GET_TRANSACTION_SUCCESS",
  GET_TRANSACTION_FAILURE: "GET_TRANSACTION_FAILURE",

  GET_GOAL_PROGRESS_BEGIN: "GET_GOAL_PROGRESS_BEGIN",
  GET_GOAL_PROGRESS_SUCCESS: "GET_GOAL_PROGRESS_SUCCESS",
  GET_GOAL_PROGRESS_FAILURE: "GET_GOAL_PROGRESS_FAILURE",

  LIKE_TRANSACTION_BEGIN: "LIKE_TRANSACTION_BEGIN",
  LIKE_TRANSACTION_SUCCESS: "LIKE_TRANSACTION_SUCCESS",
  LIKE_TRANSACTION_FAILURE: "LIKE_TRANSACTION_FAILURE",

  REMOVE_TRANSACTION_BEGIN: "REMOVE_TRANSACTION_BEGIN",
  REMOVE_TRANSACTION_SUCCESS: "REMOVE_TRANSACTION_SUCCESS",
  REMOVE_TRANSACTION_FAILURE: "REMOVE_TRANSACTION_FAILURE",

  SET_EDIT_TRANSACTION: "SET_EDIT_TRANSACTION",
};
