$LOAD_PATH << '.'

# Dir.chdir('./../')

@fastlane_directory = File.expand_path('./fastlane/helpers')
unless File.directory?(@fastlane_directory)
  @fastlane_directory = File.expand_path('./helpers')
end
require "#{@fastlane_directory}/metadata_helper.rb"

@helper = Metadata_helper.new

app_identifier            @helper.get_property("app_identifier")
username                  ENV['FASTLANE_USER']
app_rating_config_path    @helper.get_property("app_rating_config_path")
app_icon                  @helper.get_property("app_icon")
apple_watch_app_icon      @helper.get_property("apple_watch_app_icon")
price_tier                @helper.get_property("price_tier")
copyright                 @helper.get_property("copyright")
primary_category          @helper.get_property("primary_category")
secondary_category        @helper.get_property("secondary_category")
automatic_release         @helper.get_property("automatic_release")

languages(@helper.get_languages)

name(@helper.get_language_property_hash("name"))

subtitle(@helper.get_language_property_hash("short_description"))

description(@helper.get_language_property_hash("description"))

keywords(@helper.get_language_property_hash("keywords"))

promotional_text(@helper.get_language_property_hash("promotional_text"))

support_url(@helper.get_language_property_hash("support_url"))

marketing_url(@helper.get_language_property_hash("marketing_url"))

privacy_url(@helper.get_language_property_hash("privacy_url"))

app_review_information({
  first_name: @helper.get_property("app_review_information")["first_name"],
  last_name: @helper.get_property("app_review_information")["last_name"],
  phone_number: @helper.get_property("app_review_information")["phone_number"],
  email_address: @helper.get_property("app_review_information")["email_address"],
  demo_user: @helper.get_property("app_review_information")["demo_user"],
  demo_password: @helper.get_property("app_review_information")["demo_password"],
  notes: @helper.get_property("app_review_information")["notes"]
})
