$LOAD_PATH << '.'
@fastlane_directory = File.expand_path('./fastlane/helpers')
unless File.directory?(@fastlane_directory)
  @fastlane_directory = File.expand_path('./helpers')
end
require "#{@fastlane_directory}/metadata_helper.rb"
helper = Metadata_helper.new

cordova_folder = File.expand_path("./cordova")
fastlane_folder = File.expand_path("./fastlane")
cordova_config = Nokogiri::XML((File.read("#{cordova_folder}/config.xml")))
app_name = cordova_config.xpath("//xmlns:name").text


ios_version '11.1'
app_identifier helper.get_property('app_identifier')
test_target_name app_name

# A list of devices you want to take the screenshots from
 devices(helper.get_property('ios_devices'))

# Languages to create screenshots for
languages helper.get_languages

output_directory "#{fastlane_folder}/screenshots/"

project "#{cordova_folder}/platforms/ios/#{app_name}.xcodeproj"

scheme app_name
skip_helper_version_check true
ios_version "11.1"
test_target_name @app_name
reinstall_app true
erase_simulator true
skip_open_summary true
clear_previous_screenshots true
stop_after_first_error false
clean true



