export default {
  USER_SET_TOKEN: "USER_SET_TOKEN",
  USER_LOGOUT: "USER_LOGOUT",

  USER_GET_INFO_BEGIN: "USER_GET_INFO_BEGIN",
  USER_GET_INFO_SUCCESS: "USER_GET_INFO_SUCCESS",
  USER_GET_INFO_FAILURE: "USER_GET_INFO_FAILURE",

  USER_RESET_PASSWORD_BEGIN: "USER_RESET_PASSWORD_BEGIN",
  USER_RESET_PASSWORD_SUCCESS: "USER_RESET_PASSWORD_SUCCESS",
  USER_RESET_PASSWORD_FAILURE: "USER_RESET_PASSWORD_FAILURE",
};
